# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20181106_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='speakerEmail',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='univ',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dept',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='univ',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
