# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_useremail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='isAdmin',
        ),
        migrations.AddField(
            model_name='speaker',
            name='citations',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speaker',
            name='h_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speaker',
            name='i_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='speaker',
            name='is_crawled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
