# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181125_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='dept',
            field=models.CharField(default='Computer Science', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='univ',
            field=models.CharField(default='KAIST', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dept',
            field=models.CharField(default='Computer Science', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='univ',
            field=models.CharField(default='KAIST', max_length=100, null=True),
        ),
    ]
