# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20181125_1854'),
        ('accounts', '0009_auto_20181125_1752'),
    ]

    operations = [
    ]
