# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('abstract', models.TextField(max_length=3000)),
                ('place', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('title', models.CharField(max_length=300)),
                ('details', models.TextField()),
                ('req', models.CharField(choices=[('non', 'No Request'), ('add', 'Addition'), ('del', 'Deletion'), ('mod', 'Modification')], default='non', max_length=3)),
                ('abstractReq', models.TextField(default=None, max_length=3000)),
                ('placeReq', models.CharField(default=None, max_length=100)),
                ('timeReq', models.DateTimeField(default=None)),
                ('titleReq', models.CharField(default=None, max_length=300)),
                ('detailsReq', models.TextField(default=None)),
                ('rankingVector', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('rankingScore', models.DecimalField(decimal_places=0, max_digits=5)),
            ],
        ),
    ]
