# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-02 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20181102_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rankingVector',
            field=models.DecimalField(decimal_places=0, max_digits=5, null=True),
        ),
    ]
