# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181105_2027'),
        ('events', '0003_auto_20181102_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendant',
            field=models.ManyToManyField(related_name='attendant', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='creater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='creater', to='accounts.UserProfile'),
        ),
        migrations.AddField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='speacker', to='accounts.Speaker'),
        ),
        migrations.AddField(
            model_name='event',
            name='speakerReq',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakerReq', to='accounts.Speaker'),
        ),
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='events.Tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='tagsReq',
            field=models.ManyToManyField(default=None, null=True, related_name='tagsReq', to='events.Tag'),
        ),
    ]
