# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20181105_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendant',
            field=models.ManyToManyField(default=None, null=True, related_name='attendant', to='accounts.UserProfile'),
        ),
    ]
