# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20181106_0043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='event',
            name='tagsReq',
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(max_length=3000),
        ),
    ]
