# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-06 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20181106_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tags',
            field=models.ManyToManyField(default=None, related_name='tags', to='events.Tag'),
        ),
        migrations.AddField(
            model_name='event',
            name='tagsReq',
            field=models.ManyToManyField(default=None, related_name='tagsReq', to='events.Tag'),
        ),
    ]
