# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-22 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20181106_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='creater',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created', to='accounts.UserProfile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='speaker',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.Speaker'),
        ),
    ]
