# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-25 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20181124_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='rankingVector',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='rankingScore',
        ),
    ]
