# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-27 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20181125_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='imgurLReq',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='imgurl',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
