# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_auto_20181127_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='abstractReq',
            field=models.TextField(blank=True, default=None, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='detailsReq',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='imgurLReq',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='placeReq',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='speakerReq',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speakerReq', to='accounts.Speaker'),
        ),
        migrations.AlterField(
            model_name='event',
            name='tagsReq',
            field=models.ManyToManyField(blank=True, default=None, related_name='tagsReq', to='events.Tag'),
        ),
        migrations.AlterField(
            model_name='event',
            name='timeReq',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='titleReq',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
