# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20181128_1930'),
        ('events', '0017_auto_20181128_2016'),
    ]

    operations = [
    ]
