# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-29 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20181129_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='abstract',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='event',
            name='abstractReq',
            field=models.TextField(blank=True, default=None, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='details',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='event',
            name='imgurLReq',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='imgurl',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='place',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='placeReq',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='req',
            field=models.CharField(choices=[('non', 'No Request'), ('add', 'Addition'), ('del', 'Deletion'), ('mod', 'Modification')], default='non', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='titleReq',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
